#!/bin/sh
#PBS -S /bin/sh
#PBS -N flux_execution_results
#PBS -A stats_flux
#PBS -l qos=flux
#PBS -l nodes=1:procs=12,pmem=4000mb,walltime=00:20:00
#PBS -q flux
#PBS -m abe
#PBS -j oe
#PBS -V
#PBS -M datahong@umich.edu
echo "I ran on:"
cat $PBS_NODEFILE
# Let PBS handle your output
# This part is where you can pretend you have control over the flux machine
# You can do things like cd, ./movieReviews.py, etc...

# module load python-anaconda3
cd ~/EECS545FinalProject
./NewsgroupPlot.py
